name: Reddit to Telegram (OAuth)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          USER_AGENT: "VM-NBA-Bot/2.3 (by u/znambo; GitHub Actions)"
          FORCE_PROXY: "1"
          PING_ON_START: "1"       # отправить тестовое сообщение при старте
          FORCE_POST_ONE: "1"      # игнорировать state и отправить 1 верхний пост принудительно
          MEDIA_MODE: "auto"       # можно временно поставить "text_only" для диагностики
          SUBREDDIT: nba
          LISTING: hot
          LIMIT: "25"
          CHAR_LIMIT: "200"
          STATE_FILE: state_reddit_ids.json
          # USER_AGENT: "VM-Reddit-TG-Bot/2.0 (by u/YourUserName; GitHub Actions)" # <- можно вынести в Variables
        run: |
          python reddit_to_telegram_bot.py

      - name: Commit state
        run: |
          if [[ -n "$(git status --porcelain state_reddit_ids.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add state_reddit_ids.json
            git commit -m "chore: update posted Reddit IDs [skip ci]"
            git push
          fi
